# Generated by Django 4.0.3 on 2022-03-17 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPhotos',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('uploaddate', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatRatings',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('catname', models.CharField(max_length=50)),
                ('fusiness', models.IntegerField()),
                ('friendliness', models.IntegerField()),
                ('tidiness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('member_since', models.DateTimeField(auto_now_add=True, null=True)),
                ('email_id', models.CharField(default=None, max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('breeds', models.CharField(max_length=100, null=True)),
                ('about_me', models.CharField(max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentdate', models.DateTimeField(auto_now_add=True)),
                ('messageread', models.BooleanField(default=False)),
                ('messagebody', models.CharField(max_length=600, null=True)),
                ('catmessager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_account', to=settings.AUTH_USER_MODEL)),
                ('messagereceive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_account', to=settings.AUTH_USER_MODEL)),
                ('messagesend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catimessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentdate', models.DateTimeField(auto_now_add=True)),
                ('messageread', models.BooleanField(default=False)),
                ('messagebody', models.TextField(max_length=600, null=True)),
                ('catmessager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersaccount', to=settings.AUTH_USER_MODEL)),
                ('messagereceive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversaccount', to=settings.AUTH_USER_MODEL)),
                ('messagesend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersaccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
