# Generated by Django 4.0.3 on 2022-03-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('member_since', models.CharField(max_length=30)),
                ('email_id', models.CharField(default=None, max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('breeds', models.CharField(max_length=100, null=True)),
                ('about_me', models.CharField(max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=800)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.catprofile')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
