# Generated by Django 4.0.3 on 2022-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPhotos',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
