# Generated by Django 4.0.3 on 2022-03-09 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_catphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catphotos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
