# Generated by Django 4.0.3 on 2022-03-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_catphotos_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catphotos',
            old_name='created_at',
            new_name='uploaddate',
        ),
    ]
