# Generated by Django 4.0.3 on 2022-03-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_created_at_catphotos_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catphotos',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
