# Generated by Django 2.1.5 on 2022-03-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatProfile',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=30)),
                ('friendliness', models.FloatField(default=3.0)),
                ('tidiness', models.FloatField(default=3.0)),
                ('fussiness', models.FloatField(default=3.0)),
                ('description', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
